import { describe, expect, it, vi } from 'vitest';

import {
  createMigratingAuthStorage,
  isSupabaseAuthStorageKey,
  supabaseAuthStorageKeyFromUrl,
  type AsyncKeyValueStorage,
  type EnumerableKeyValueStorage,
} from '@/services/auth-storage-core';

const storageKey = 'sb-project-auth-token';

describe('Supabase auth storage key derivation', () => {
  it('matches the key generated by the Supabase client for hosted and local URLs', () => {
    expect(supabaseAuthStorageKeyFromUrl('https://project.supabase.co')).toBe(storageKey);
    expect(supabaseAuthStorageKeyFromUrl('http://127.0.0.1:54321')).toBe('sb-127-auth-token');
  });

  it.each([undefined, '', 'not a URL', 'ftp://project.supabase.co'])('rejects %s without throwing', (value) => {
    expect(supabaseAuthStorageKeyFromUrl(value)).toBeNull();
  });
});

function createStores(options: Record<string, { secure?: string; legacy?: string }> = {}) {
  const secureValues = new Map<string, string>();
  const legacyValues = new Map<string, string>();
  for (const [key, values] of Object.entries(options)) {
    if (values.secure !== undefined) secureValues.set(key, values.secure);
    if (values.legacy !== undefined) legacyValues.set(key, values.legacy);
  }

  const secure: AsyncKeyValueStorage = {
    getItem: vi.fn(async (key) => secureValues.get(key) ?? null),
    setItem: vi.fn(async (key, value) => {
      secureValues.set(key, value);
    }),
    removeItem: vi.fn(async (key) => {
      secureValues.delete(key);
    }),
  };
  const legacy: EnumerableKeyValueStorage = {
    getAllKeys: vi.fn(async () => [...legacyValues.keys()]),
    getItem: vi.fn(async (key) => legacyValues.get(key) ?? null),
    setItem: vi.fn(async (key, value) => {
      legacyValues.set(key, value);
    }),
    removeItem: vi.fn(async (key) => {
      legacyValues.delete(key);
    }),
  };

  return { secure, legacy, secureValues, legacyValues };
}

function createStorage(
  secure: AsyncKeyValueStorage,
  legacy: EnumerableKeyValueStorage,
) {
  return createMigratingAuthStorage(
    secure,
    legacy,
    (key) => isSupabaseAuthStorageKey(storageKey, key),
  );
}

describe('Supabase auth storage key matching', () => {
  it.each([
    storageKey,
    `${storageKey}-user`,
    `${storageKey}-code-verifier`,
    `${storageKey}-flows-code-verifier`,
    `${storageKey}-flow-flow-id-code-verifier`,
  ])('includes %s', (key) => {
    expect(isSupabaseAuthStorageKey(storageKey, key)).toBe(true);
  });

  it.each([
    `${storageKey}-flow-flow-id`,
    `${storageKey}-unrelated`,
    'app-setting',
  ])('excludes %s', (key) => {
    expect(isSupabaseAuthStorageKey(storageKey, key)).toBe(false);
  });
});

describe('createMigratingAuthStorage', () => {
  it('moves every matching plaintext auth value and leaves unrelated settings alone', async () => {
    const pkceKey = `${storageKey}-flow-flow-id-code-verifier`;
    const { secure, legacy, secureValues, legacyValues } = createStores({
      [storageKey]: { legacy: 'legacy-session' },
      [pkceKey]: { legacy: 'legacy-verifier' },
      'app-setting': { legacy: 'keep-me' },
    });
    const storage = createStorage(secure, legacy);

    await expect(storage.getItem(storageKey)).resolves.toBe('legacy-session');
    expect(secureValues.get(pkceKey)).toBe('legacy-verifier');
    expect(legacyValues.has(storageKey)).toBe(false);
    expect(legacyValues.has(pkceKey)).toBe(false);
    expect(legacyValues.get('app-setting')).toBe('keep-me');
  });

  it('prefers secure storage and removes a leftover plaintext copy', async () => {
    const { secure, legacy, secureValues, legacyValues } = createStores({
      [storageKey]: { secure: 'secure-session', legacy: 'stale-session' },
    });
    const storage = createStorage(secure, legacy);

    await expect(storage.getItem(storageKey)).resolves.toBe('secure-session');
    expect(secureValues.get(storageKey)).toBe('secure-session');
    expect(legacyValues.has(storageKey)).toBe(false);
  });

  it('returns null when neither storage has a value', async () => {
    const { secure, legacy } = createStores();
    const storage = createStorage(secure, legacy);

    await expect(storage.getItem(storageKey)).resolves.toBeNull();
  });

  it('does not delete the only session when secure migration fails and retries later', async () => {
    const { secure, legacy, legacyValues } = createStores({
      [storageKey]: { legacy: 'legacy-session' },
    });
    vi.mocked(secure.setItem).mockRejectedValueOnce(new Error('secure store unavailable'));
    const storage = createStorage(secure, legacy);

    await expect(storage.getItem(storageKey)).rejects.toThrow('secure store unavailable');
    expect(legacyValues.get(storageKey)).toBe('legacy-session');
    await expect(storage.getItem(storageKey)).resolves.toBe('legacy-session');
  });

  it('writes securely before removing a plaintext remainder', async () => {
    const { secure, legacy } = createStores({
      [storageKey]: { legacy: 'old-session' },
    });
    const storage = createStorage(secure, legacy);
    await storage.getItem(storageKey);
    vi.clearAllMocks();

    await storage.setItem(storageKey, 'new-session');

    expect(secure.setItem).toHaveBeenCalledWith(storageKey, 'new-session');
    expect(legacy.removeItem).toHaveBeenCalledWith(storageKey);
    expect(vi.mocked(secure.setItem).mock.invocationCallOrder[0])
      .toBeLessThan(vi.mocked(legacy.removeItem).mock.invocationCallOrder[0]);
  });

  it('removes plaintext before secure data so a failed cleanup cannot revive a session', async () => {
    const { secure, legacy } = createStores({
      [storageKey]: { secure: 'secure-session' },
    });
    const storage = createStorage(secure, legacy);
    await storage.getItem(storageKey);
    vi.clearAllMocks();

    await storage.removeItem(storageKey);

    expect(vi.mocked(legacy.removeItem).mock.invocationCallOrder[0])
      .toBeLessThan(vi.mocked(secure.removeItem).mock.invocationCallOrder[0]);
  });

  it('serializes operations for the same key', async () => {
    const { secure, legacy, secureValues } = createStores();
    const storage = createStorage(secure, legacy);
    await storage.getItem(storageKey);
    let releaseFirstWrite: (() => void) | undefined;
    vi.mocked(secure.setItem).mockImplementationOnce(async (key, value) => {
      await new Promise<void>((resolve) => {
        releaseFirstWrite = resolve;
      });
      secureValues.set(key, value);
    });

    const first = storage.setItem(storageKey, 'first');
    const second = storage.setItem(storageKey, 'second');
    await vi.waitFor(() => expect(releaseFirstWrite).toBeTypeOf('function'));
    expect(secureValues.has(storageKey)).toBe(false);
    releaseFirstWrite?.();
    await Promise.all([first, second]);

    expect(secureValues.get(storageKey)).toBe('second');
  });
});
